
export  class  Constants{
  // 自定义标题栏
  static readonly TYPE_LEFT_NONE: number = 0;
  static readonly TYPE_LEFT_TEXT_VIEW: number = 1;
  static readonly TYPE_LEFT_IMAGE_VIEW: number = 2;
  static readonly TYPE_LEFT_CUSTOM_VIEW: number = 3;

  static readonly TYPE_RIGHT_NONE: number = 0;
  static readonly TYPE_RIGHT_TEXT_VIEW: number = 1;
  static readonly TYPE_RIGHT_IMAGE_VIEW: number = 2;
  static readonly TYPE_RIGHT_CUSTOM_VIEW: number = 3;

  static readonly TYPE_CENTER_NONE: number = 0;
  static readonly TYPE_CENTER_TEXT_VIEW: number = 1;
  static readonly TYPE_CENTER_IMAGE_VIEW: number = 2;
  static readonly TYPE_CENTER_CUSTOM_VIEW: number = 3;
  static readonly TYPE_CENTER_SEARCH_VIEW: number = 4;
}