# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Easemob_UIkit_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'EaseChatUIKit'
  pod 'Kingfisher'
  # Pods for Easemob_UIkit_Demo

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
